language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "node"
  - 10
  - 8

install:
  - npm install

script:
  - npm run lint
  - npm run format:check
  - npm test
  - npm run coverage
