language: node_js

cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store

node_js: "14"

install:
  - pnpm install

script: pnpm run ci
