version: 2.1

jobs:
  build:
    docker:
      - image: node:20
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: install
          command: pnpm install
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: pnpm build
      - run:
          name: lint
          command: pnpm lint
      - run:
          name: format
          command: pnpm format:check
