import React, { Fragment } from 'react';

export default () => (
    <Fragment>
        <h2>Privacy notice</h2>
        <p>
            My website may be used without entering personal information.
            Different rules may apply to certain services on my site, however,
            and are explained separately below. Information is considered
            personal if it can be associated exclusively to a specific natural
            person. The legal framework for data protection may be found in the
            German Federal Data Protection Act (BDSG) and the Telemedia Act
            (TMG). The provisions below serve to provide information as to the
            manner, extent and purpose for collecting, using and processing
            personal information.
        </p>
        <p>
            Please be aware that data transfer via the internet is subject to
            security risks and, therefore, complete protection against
            third-party access to transferred data cannot be ensured.
        </p>
        <h3>Cookies</h3>
        <p>
            My website makes use of so-called cookies in order to recognize
            repeat use of my website by the same user/internet connection
            subscriber. Cookies are small text files that your internet browser
            downloads and stores on your computer. They are used to improve our
            website and services. In most cases these are so-called
            &quot;session cookies&quot; that are deleted once you leave my
            website.
        </p>
        <p>
            To an extent, however, these cookies also pass along information
            used to automatically recognize you. Recognition occurs through an
            IP address saved to the cookies. The information thereby obtained is
            used to improve my service and to expedite your access to the
            website.
        </p>
        <p>
            You can prevent cookies from being installed by adjusting the
            settings on your browser software accordingly. You should be aware,
            however, that by doing so you may not be able to make full use of
            all the functions of this website.
        </p>
        <h3>Use of Google Analytics with anonymization</h3>
        <p>
            My website uses Google Analytics, a web analysis service from Google
            Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043 USA,
            hereinafter referred to as &quot;Google&quot;. Google Analytics
            employs so-called &quot;cookies&quot;, text files that are stored to
            your computer in order to facilitate an analysis of your use of the
            site.
        </p>
        <p>
            The information generated by these cookies, such as time, place and
            frequency of your visits to our site, including your IP address, is
            transmitted to Google’s location in the US and stored there.
        </p>
        <p>
            I use Google Analytics with an IP anonymization feature on my
            website. In doing so, Google abbreviates and thereby anonymizes your
            IP address before transferring it from member states of the European
            Union or signatory states to the Agreement on the European Economic
            Area.
        </p>
        <p>
            Google will use this information to evaluate your usage of my site,
            to compile reports on website activity for my, and to provide other
            services related to website- and internet usage. Google may also
            transfer this information to third parties if this is required by
            law or to the extent this data is processed by third parties on
            Google&apos;s behalf.
        </p>
        <p>
            Google states that it will in never associate your IP address with
            other data held by Google. You can prevent cookies from being
            installed by adjusting the settings on your browser software
            accordingly. You should be aware, however, that by doing so you may
            not be able to make full use of all the functions of this website.
        </p>
        <p>
            Google also offers a disabling option for the most common browsers,
            thus providing you with greater control over the data which is
            collected and processed by Google. If you enable this option, no
            information regarding your website visit is transmitted to Google
            Analytics. However, the activation does not prevent the transmission
            of information to me or to any other web analytics services I may
            use. For more information about the disabling option provided by
            Google, and how to enable this option, visit{' '}
            <a href="https://tools.google.com/dlpage/gaoptout?hl=en">
                https://tools.google.com/dlpage/gaoptout?hl=en
            </a>{' '}
            or click the following link to only disable tracking for this site:{' '}
            {/* eslint-disable */}
            <a href="javascript:gaOptout();">Deactive Google Analytics</a>
            {/* eslint-enable */}
        </p>
        <h3>Information/Cancellation/Deletion</h3>
        <p>
            On the basis of the Federal Data Protection Act, you may contact my
            at no cost if you have questions relating to the collection,
            processing or use of your personal information, if you wish to
            request the correction, blocking or deletion of the same, or if you
            wish to cancel explicitly granted consent. Please note that you have
            the right to have incorrect data corrected or to have personal data
            deleted, where such claim is not barred by any legal obligation to
            retain this data.
        </p>
    </Fragment>
);
